name: e-commerce-shop

volumes:
  cache:
    driver: local

services:
  redis:
    image: redis:7.2-rc-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass ZGlhY2hlbmtvNjUx

  database:
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: diachenko
      POSTGRES_DB: ecommerceshop
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  backend:
    restart: always
    build:
      dockerfile: backend/Dockerfile
      args:
        JAR_FILE: backend/target/backend-1.0-SNAPSHOT-exec.jar
    volumes:
      - ./images/:/app/images/
    ports:
      - '8080:8080'

#  frontend:
#    build:
#      context: ./e-commerce-frontend
#      dockerfile: Dockerfile
#    container_name: angular-app
#    ports:
#      - '4200:4200'
#    environment:
#      - CHOKIDAR_USEPOLLING = true # For live reload in Docker
#    volumes:
#      - ./e-commerce-frontend:/angular-app
#    depends_on:
#      - backend