spring:
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: 172.17.0.1
      port: 6379
      password: ZGlhY2hlbmtvNjUx
#  web:
#    resources:
#      static-locations: file:/app/images/
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB
  application:
    name: 'Backend'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.0.1:5433/ecommerceshop
#    url: jdbc:postgresql://localhost:5433/ecommerceshop
    username: postgres
    password: diachenko
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    logging:
        level:
          org.hibernate.SQL: DEBUG
          org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: "none"  # Используем Flyway вместо JPA для создания схемы
    flyway:
      enabled: true
      locations: classpath:db/migration


